import { getMission } from '../domain/missions';
import type { MissionId, ProcessStep } from '../domain/contracts';
import { createInitialSession } from './labReducer';
import type { LabSession } from './contracts';
import { validSessionShape } from './sessionValidation';
export const STORAGE_KEY = 'mixture-separation-process-lab:v1';
const cleanStep = (s: any) => ({ id: s.id, actionId: s.actionId, input: s.input.source === 'initial' ? { source: 'initial' } : { source: 'step', stepId: s.input.stepId, port: s.input.port }, evidencePropertyId: s.evidencePropertyId, params: s.actionId === 'sieve' ? { gap: s.params.gap } : {} });
const cleanRun = (r: any) => r === null ? null : JSON.parse(JSON.stringify(r));
export function serializeSession(s: LabSession): string { const ids = new Set(s.draftPlan.map((p) => p.id)); const copy = { schemaVersion: 1 as const, stage: s.stage, attempt: s.attempt, missionId: s.missionId, selectedTargetIds: [...s.selectedTargetIds], confirmedPropertyIds: [...s.confirmedPropertyIds], draftPlan: s.draftPlan.map(cleanStep), planHistory: s.planHistory.map((p) => p.map(cleanStep)), initialPlan: s.initialPlan ? s.initialPlan.map(cleanStep) : null, revisedPlan: s.revisedPlan ? s.revisedPlan.map(cleanStep) : null, predictions: Object.fromEntries(Object.entries(s.predictions).filter(([k]) => ids.has(k)).map(([k,v]) => [k,v])), completedStepIds: [...s.completedStepIds], currentRun: cleanRun(s.currentRun), recoveryClaims: s.recoveryClaims.map((c) => ({ materialId: c.materialId, streamId: c.streamId })), revisionReason: s.revisionReason, sustainabilityReflection: s.sustainabilityReflection }; return JSON.stringify(copy); }
function valid(x: any): x is LabSession { return validSessionShape(x); }
export function loadSession(storage: Pick<Storage, 'getItem'>): LabSession { try { const raw = storage.getItem(STORAGE_KEY); if (!raw) return createInitialSession(); const x = JSON.parse(raw); if (!valid(x)) return createInitialSession(); if (x.missionId) getMission(x.missionId as MissionId); return { schemaVersion: 1, stage: x.stage, attempt: x.attempt, missionId: x.missionId, selectedTargetIds: [...x.selectedTargetIds], confirmedPropertyIds: [...x.confirmedPropertyIds], draftPlan: [...x.draftPlan] as ProcessStep[], planHistory: x.planHistory.map((p: readonly ProcessStep[]) => [...p]), initialPlan: x.initialPlan ? [...x.initialPlan] as ProcessStep[] : null, revisedPlan: x.revisedPlan ? [...x.revisedPlan] as ProcessStep[] : null, predictions: { ...x.predictions }, completedStepIds: [...x.completedStepIds], currentRun: x.currentRun ?? null, recoveryClaims: [...x.recoveryClaims], revisionReason: x.revisionReason, sustainabilityReflection: x.sustainabilityReflection }; } catch { return createInitialSession(); } }
export function saveSession(storage: Pick<Storage, 'setItem'>, state: LabSession): void { storage.setItem(STORAGE_KEY, serializeSession(state)); }
