import type { ProcessStep } from '../domain/contracts';
import type { SimulationRun } from '../simulation/contracts';
const materials = new Set(['gravel','sand','salt','water','oil']); const properties = new Set(['particle-size','immiscibility','water-solubility','filter-behavior','evaporation-residue']); const missions = new Set(['size-sort','liquid-layers','salt-recovery','integrated-process']); const ports = new Set(['mixture','layered-mixture','pass','retained','upper','lower','filtrate','filter-residue','vapor-model','solid-residue','unchanged']);
export const rec = (x: unknown): x is Record<string, any> => Boolean(x) && typeof x === 'object' && !Array.isArray(x);
const stream = (x: any) => rec(x) && ((x.source === 'initial' && Object.keys(x).length === 1) || (x.source === 'step' && typeof x.stepId === 'string' && ports.has(x.port) && Object.keys(x).length === 3));
export function validStep(x: unknown): x is ProcessStep { if (!rec(x) || typeof x.id !== 'string' || !stream(x.input) || !rec(x.params)) return false; const e: Record<string,string> = { sieve:'particle-size', 'layer-separation':'immiscibility', filtration:'filter-behavior', 'virtual-evaporation':'evaporation-residue', 'add-water':'water-solubility', 'wait-for-layers':'immiscibility' }; if (!(x.actionId in e) || x.evidencePropertyId !== e[x.actionId]) return false; return x.actionId === 'sieve' ? Object.keys(x.params).length === 1 && ['wide-gap','medium-gap','fine-gap'].includes(x.params.gap) : Object.keys(x.params).length === 0; }
const strings = (x: unknown, set?: Set<string>) => Array.isArray(x) && x.every((v) => typeof v === 'string' && (!set || set.has(v)));
function validRun(x: any): x is SimulationRun { if (!rec(x) || !missions.has(x.missionId) || !rec(x.tokens) || !rec(x.streams) || !Array.isArray(x.outcomes) || !Array.isArray(x.movements) || !Array.isArray(x.lostTokenIds) || !strings(x.lostTokenIds) || !strings(x.initialTokenIds) || !strings(x.activeLeafStreamIds) || !rec(x.finalLocationByTokenId) || !Array.isArray(x.planIssues)) return false; if (!Object.values(x.tokens).every((t:any)=>rec(t)&&typeof t.id==='string'&&materials.has(t.materialId)&&['initial','added-carrier'].includes(t.origin)&&['solid','liquid','dissolved'].includes(t.phase))) return false; if (!Object.values(x.streams).every((s:any)=>rec(s)&&typeof s.id==='string'&&strings(s.tokenIds)&&rec(s.condition)&&typeof s.condition.waterAdded==='boolean'&&typeof s.condition.layersSettled==='boolean'&&(s.consumedByStepId===null||typeof s.consumedByStepId==='string'))) return false; if (!x.outcomes.every((o:any)=>rec(o)&&typeof o.stepId==='string'&&typeof o.actionId==='string'&&['applied','no-basis'].includes(o.status)&&(o.reasonCode===null||typeof o.reasonCode==='string')&&typeof o.explanation==='string'&&rec(o.tokens)&&Array.isArray(o.outputs)&&Array.isArray(o.movements)&&Array.isArray(o.addedTokenIds)&&Array.isArray(o.lostTokenIds))) return false; if (!x.movements.every((m:any)=>rec(m)&&typeof m.tokenId==='string'&&typeof m.stepId==='string'&&typeof m.fromStreamId==='string'&&(typeof m.toStreamId==='string')&&typeof m.reason==='string')) return false; return x.planIssues.every((p:any)=>rec(p)&&typeof p.code==='string'&&typeof p.stepId==='string'&&typeof p.message==='string'); }
export function validSessionShape(x: any): boolean { return rec(x)&&x.schemaVersion===1&&['intake','properties','design','simulation','quality','revision','report'].includes(x.stage)&&['initial','revised'].includes(x.attempt)&&(x.missionId===null||missions.has(x.missionId))&&strings(x.selectedTargetIds,materials)&&strings(x.confirmedPropertyIds,properties)&&Array.isArray(x.draftPlan)&&x.draftPlan.every(validStep)&&Array.isArray(x.planHistory)&&x.planHistory.every((p:any)=>Array.isArray(p)&&p.every(validStep))&&(x.initialPlan===null||Array.isArray(x.initialPlan)&&x.initialPlan.every(validStep))&&(x.revisedPlan===null||Array.isArray(x.revisedPlan)&&x.revisedPlan.every(validStep))&&rec(x.predictions)&&Object.entries(x.predictions).every(([k,v])=>typeof k==='string'&&typeof v==='string'&&ports.has(v as string))&&strings(x.completedStepIds)&&Array.isArray(x.recoveryClaims)&&x.recoveryClaims.every((c:any)=>rec(c)&&materials.has(c.materialId)&&typeof c.streamId==='string')&&(x.currentRun===null||validRun(x.currentRun))&&typeof x.revisionReason==='string'&&typeof x.sustainabilityReflection==='string'; }
