import type { ProcessStep } from '../domain/contracts';
import type { SimulationRun } from '../simulation/contracts';
const sets: Record<string, Set<string>> = {
  mission: new Set(['size-sort','liquid-layers','salt-recovery','integrated-process']), material: new Set(['gravel','sand','salt','water','oil']), property: new Set(['particle-size','immiscibility','water-solubility','filter-behavior','evaporation-residue']), action: new Set(['sieve','layer-separation','filtration','virtual-evaporation','add-water','wait-for-layers']), port: new Set(['mixture','layered-mixture','pass','retained','upper','lower','filtrate','filter-residue','vapor-model','solid-residue','unchanged']), issue: new Set(['duplicate-step-id','action-not-allowed','property-not-confirmed','invalid-evidence','input-not-found','input-already-consumed','future-input-reference']), reason: new Set(['missing-water','layers-not-settled','no-size-contrast','no-filter-contrast','no-dissolved-solid','unsupported-mixture']),
};
export const rec = (x: unknown): x is Record<string, any> => Boolean(x) && typeof x === 'object' && !Array.isArray(x);
export const exactKeys = (x: any, keys: string[]) => rec(x) && Object.keys(x).length === keys.length && keys.every((k) => k in x);
const arr = (x: any, set?: Set<string>) => Array.isArray(x) && x.every((v) => typeof v === 'string' && (!set || set.has(v)));
const ref = (x: any) => (exactKeys(x,['source']) && x.source === 'initial') || (exactKeys(x,['source','stepId','port']) && x.source === 'step' && typeof x.stepId === 'string' && sets.port.has(x.port));
export function validStep(x: any): x is ProcessStep { if (!exactKeys(x,['id','actionId','input','evidencePropertyId','params']) || typeof x.id !== 'string' || !sets.action.has(x.actionId) || !ref(x.input) || !rec(x.params)) return false; const e: any = { sieve:'particle-size','layer-separation':'immiscibility',filtration:'filter-behavior','virtual-evaporation':'evaporation-residue','add-water':'water-solubility','wait-for-layers':'immiscibility' }; return x.evidencePropertyId === e[x.actionId] && (x.actionId === 'sieve' ? exactKeys(x.params,['gap']) && ['wide-gap','medium-gap','fine-gap'].includes(x.params.gap) : exactKeys(x.params,[])); }
const token = (x:any) => exactKeys(x,['id','materialId','origin','phase']) && typeof x.id === 'string' && sets.material.has(x.materialId) && ['initial','added-carrier'].includes(x.origin) && ['solid','liquid','dissolved'].includes(x.phase);
const stream = (x:any) => exactKeys(x,['id','tokenIds','condition','consumedByStepId']) && typeof x.id === 'string' && arr(x.tokenIds) && exactKeys(x.condition,['waterAdded','layersSettled']) && typeof x.condition.waterAdded === 'boolean' && typeof x.condition.layersSettled === 'boolean' && (x.consumedByStepId === null || typeof x.consumedByStepId === 'string');
const move = (x:any) => exactKeys(x,['tokenId','stepId','fromStreamId','toStreamId','reason']) && ['tokenId','stepId','fromStreamId','toStreamId','reason'].every((k) => typeof x[k] === 'string');
const outcome = (x:any) => exactKeys(x,['stepId','actionId','status','reasonCode','explanation','tokens','outputs','movements','addedTokenIds','lostTokenIds']) && typeof x.stepId === 'string' && sets.action.has(x.actionId) && ['applied','no-basis'].includes(x.status) && (x.reasonCode === null || sets.reason.has(x.reasonCode)) && typeof x.explanation === 'string' && rec(x.tokens) && Object.values(x.tokens).every(token) && Array.isArray(x.outputs) && x.outputs.every((p:any) => exactKeys(p,['port','stream']) && sets.port.has(p.port) && stream(p.stream)) && Array.isArray(x.movements) && x.movements.every(move) && arr(x.addedTokenIds) && arr(x.lostTokenIds);
export function validRun(x:any, mission?:string): x is SimulationRun { if (!exactKeys(x,['missionId','tokens','streams','outcomes','movements','lostTokenIds','initialTokenIds','activeLeafStreamIds','finalLocationByTokenId','planIssues']) || !sets.mission.has(x.missionId) || (mission !== undefined && x.missionId !== mission) || !rec(x.tokens) || !rec(x.streams) || !(Object.entries(x.tokens) as any[]).every(([k,v]) => token(v) && v.id === k) || !(Object.entries(x.streams) as any[]).every(([k,v]) => stream(v) && v.id === k) || !Array.isArray(x.outcomes) || !x.outcomes.every(outcome) || !Array.isArray(x.movements) || !x.movements.every(move) || !arr(x.lostTokenIds) || !arr(x.initialTokenIds) || !arr(x.activeLeafStreamIds) || !x.activeLeafStreamIds.every((id:string) => id in x.streams) || !rec(x.finalLocationByTokenId) || !(Object.values(x.finalLocationByTokenId) as any[]).every((v) => typeof v === 'string' || v === 'loss') || !Array.isArray(x.planIssues) || !x.planIssues.every((p:any) => exactKeys(p,['code','stepId','message']) && sets.issue.has(p.code) && typeof p.stepId === 'string' && typeof p.message === 'string')) return false; const tids = new Set(Object.keys(x.tokens)); const ids = (a:any[]) => a.every((id) => tids.has(id)); return ids(x.lostTokenIds) && ids(x.initialTokenIds) && Object.values(x.streams).every((s:any) => s.tokenIds.every((id:string) => tids.has(id))) && x.outcomes.every((o:any) => ids(o.addedTokenIds) && ids(o.lostTokenIds) && o.outputs.every((p:any) => p.stream.tokenIds.every((id:string) => tids.has(id)))); }
export function validSessionShape(x:any): boolean { return exactKeys(x,['schemaVersion','stage','attempt','missionId','selectedTargetIds','confirmedPropertyIds','draftPlan','planHistory','initialPlan','revisedPlan','predictions','completedStepIds','currentRun','recoveryClaims','revisionReason','sustainabilityReflection']) && x.schemaVersion === 1 && ['intake','properties','design','simulation','quality','revision','report'].includes(x.stage) && ['initial','revised'].includes(x.attempt) && (x.missionId === null || sets.mission.has(x.missionId)) && arr(x.selectedTargetIds,sets.material) && arr(x.confirmedPropertyIds,sets.property) && Array.isArray(x.draftPlan) && x.draftPlan.every(validStep) && Array.isArray(x.planHistory) && x.planHistory.every((p:any) => Array.isArray(p) && p.every(validStep)) && (x.initialPlan === null || Array.isArray(x.initialPlan) && x.initialPlan.every(validStep)) && (x.revisedPlan === null || Array.isArray(x.revisedPlan) && x.revisedPlan.every(validStep)) && rec(x.predictions) && (Object.values(x.predictions) as any[]).every((v) => typeof v === 'string' && sets.port.has(v)) && arr(x.completedStepIds) && Array.isArray(x.recoveryClaims) && x.recoveryClaims.every((c:any) => exactKeys(c,['materialId','streamId']) && sets.material.has(c.materialId) && typeof c.streamId === 'string') && (x.currentRun === null || validRun(x.currentRun,x.missionId || undefined)) && typeof x.revisionReason === 'string' && typeof x.sustainabilityReflection === 'string'; }
