// @ts-nocheck Runtime validation intentionally operates on unknown JSON.
import type { ProcessStep } from '../domain/contracts';
import type { SimulationRun } from '../simulation/contracts';
const values = { mission:['size-sort','liquid-layers','salt-recovery','integrated-process'], material:['gravel','sand','salt','water','oil'], property:['particle-size','immiscibility','water-solubility','filter-behavior','evaporation-residue'], action:['sieve','layer-separation','filtration','virtual-evaporation','add-water','wait-for-layers'], port:['mixture','layered-mixture','pass','retained','upper','lower','filtrate','filter-residue','vapor-model','solid-residue','unchanged'], issue:['duplicate-step-id','action-not-allowed','property-not-confirmed','invalid-evidence','input-not-found','input-already-consumed','future-input-reference'], reason:['missing-water','layers-not-settled','no-size-contrast','no-filter-contrast','no-dissolved-solid','unsupported-mixture'] };
const sets = Object.fromEntries(Object.entries(values).map(([key,list]) => [key,new Set(list)]));
const isRecord = (x: unknown): x is Record<string, any> => Boolean(x) && typeof x === 'object' && !Array.isArray(x);
export const rec = isRecord;
export const exactKeys = (x: unknown, keys: readonly string[]) => isRecord(x) && Object.keys(x).length === keys.length && keys.every((key) => Object.prototype.hasOwnProperty.call(x,key));
const unique = (x: unknown[]) => new Set(x).size === x.length;
const idArray = (x: unknown, set?: Set<string>) => Array.isArray(x) && unique(x) && x.every((v) => typeof v === 'string' && (!set || set.has(v)));
const streamRef = (x: any) => (exactKeys(x,['source']) && x.source === 'initial') || (exactKeys(x,['source','stepId','port']) && x.source === 'step' && typeof x.stepId === 'string' && sets.port.has(x.port));
export function validStep(x: any): x is ProcessStep { if (!exactKeys(x,['id','actionId','input','evidencePropertyId','params']) || typeof x.id !== 'string' || !x.id || !sets.action.has(x.actionId) || !streamRef(x.input)) return false; const evidence:any={sieve:'particle-size','layer-separation':'immiscibility',filtration:'filter-behavior','virtual-evaporation':'evaporation-residue','add-water':'water-solubility','wait-for-layers':'immiscibility'}; if (x.evidencePropertyId !== evidence[x.actionId]) return false; return x.actionId === 'sieve' ? exactKeys(x.params,['gap']) && ['wide-gap','medium-gap','fine-gap'].includes(x.params.gap) : exactKeys(x.params,[]); }
const validToken = (x:any) => exactKeys(x,['id','materialId','origin','phase']) && typeof x.id === 'string' && Boolean(x.id) && sets.material.has(x.materialId) && ['initial','added-carrier'].includes(x.origin) && ['solid','liquid','dissolved'].includes(x.phase);
const validTokenMap = (x:any) => isRecord(x) && Object.entries(x).every(([key,token]) => validToken(token) && token.id === key);
const validCondition = (x:any) => exactKeys(x,['waterAdded','layersSettled']) && typeof x.waterAdded === 'boolean' && typeof x.layersSettled === 'boolean';
const validStream = (x:any, tokenIds?:Set<string>) => exactKeys(x,['id','tokenIds','condition','consumedByStepId']) && typeof x.id === 'string' && Boolean(x.id) && idArray(x.tokenIds) && validCondition(x.condition) && (x.consumedByStepId === null || typeof x.consumedByStepId === 'string') && (!tokenIds || x.tokenIds.every((id:string) => tokenIds.has(id)));
const validStreamMap = (x:any, tokenIds:Set<string>) => isRecord(x) && Object.entries(x).every(([key,stream]) => validStream(stream,tokenIds) && stream.id === key);
const validMovement = (x:any) => exactKeys(x,['tokenId','stepId','fromStreamId','toStreamId','reason']) && ['tokenId','stepId','fromStreamId','toStreamId','reason'].every((key) => typeof x[key] === 'string');
const validOutput = (x:any, tokenIds:Set<string>) => exactKeys(x,['port','stream']) && sets.port.has(x.port) && validStream(x.stream,tokenIds);
const validOutcome = (x:any, allTokenIds:Set<string>) => { if (!exactKeys(x,['stepId','actionId','status','reasonCode','explanation','tokens','outputs','movements','addedTokenIds','lostTokenIds']) || typeof x.stepId !== 'string' || !sets.action.has(x.actionId) || !['applied','no-basis'].includes(x.status) || typeof x.explanation !== 'string' || !validTokenMap(x.tokens)) return false; if (x.status === 'applied' ? x.reasonCode !== null : !sets.reason.has(x.reasonCode)) return false; const tokenIds=new Set(Object.keys(x.tokens)); return Array.isArray(x.outputs) && x.outputs.every((output:any) => validOutput(output,tokenIds)) && Array.isArray(x.movements) && x.movements.every((movement:any) => validMovement(movement) && movement.stepId === x.stepId && tokenIds.has(movement.tokenId)) && idArray(x.addedTokenIds) && idArray(x.lostTokenIds) && x.addedTokenIds.every((id:string) => allTokenIds.has(id)) && x.lostTokenIds.every((id:string) => allTokenIds.has(id)) && x.outputs.every((output:any) => output.stream.tokenIds.every((id:string) => tokenIds.has(id))); };
const exactKeySet = (record:Record<string,unknown>, expected:Set<string>) => Object.keys(record).length === expected.size && Object.keys(record).every((key) => expected.has(key));
export function validRun(x:any, mission?:string): x is SimulationRun { if (!exactKeys(x,['missionId','tokens','streams','outcomes','movements','lostTokenIds','initialTokenIds','activeLeafStreamIds','finalLocationByTokenId','planIssues']) || !sets.mission.has(x.missionId) || (mission !== undefined && x.missionId !== mission) || !validTokenMap(x.tokens)) return false; const tokenIds=new Set(Object.keys(x.tokens)); if (!validStreamMap(x.streams,tokenIds) || !Array.isArray(x.outcomes) || !unique(x.outcomes.map((outcome:any) => outcome?.stepId)) || !x.outcomes.every((outcome:any) => validOutcome(outcome,tokenIds)) || !Array.isArray(x.movements) || !x.movements.every((movement:any) => validMovement(movement) && tokenIds.has(movement.tokenId) && x.outcomes.some((outcome:any) => outcome.stepId === movement.stepId) && x.streams[movement.fromStreamId] && (movement.toStreamId === 'loss' || x.streams[movement.toStreamId]))) return false; if (!idArray(x.lostTokenIds) || !idArray(x.initialTokenIds) || !idArray(x.activeLeafStreamIds) || !x.lostTokenIds.every((id:string) => tokenIds.has(id)) || !x.initialTokenIds.every((id:string) => tokenIds.has(id)) || !x.activeLeafStreamIds.every((id:string) => Boolean(x.streams[id])) || !exactKeySet(x.finalLocationByTokenId,tokenIds) || !Object.values(x.finalLocationByTokenId).every((id:any) => id === 'loss' || Boolean(x.streams[id]))) return false; return Array.isArray(x.planIssues) && x.planIssues.every((issue:any) => exactKeys(issue,['code','stepId','message']) && sets.issue.has(issue.code) && typeof issue.stepId === 'string' && typeof issue.message === 'string'); }
export function validSessionShape(x:any): boolean { if (!exactKeys(x,['schemaVersion','stage','attempt','missionId','selectedTargetIds','confirmedPropertyIds','draftPlan','planHistory','initialPlan','revisedPlan','predictions','completedStepIds','currentRun','recoveryClaims','revisionReason','sustainabilityReflection']) || x.schemaVersion !== 1 || !['intake','properties','design','simulation','quality','revision','report'].includes(x.stage) || !['initial','revised'].includes(x.attempt) || (x.missionId !== null && !sets.mission.has(x.missionId))) return false; const plan=(value:any) => Array.isArray(value) && unique(value.map((step:any) => step?.id)) && value.every(validStep); if (!idArray(x.selectedTargetIds,sets.material) || !idArray(x.confirmedPropertyIds,sets.property) || !plan(x.draftPlan) || !Array.isArray(x.planHistory) || !x.planHistory.every(plan) || !(x.initialPlan === null || plan(x.initialPlan)) || !(x.revisedPlan === null || plan(x.revisedPlan)) || !isRecord(x.predictions) || !Object.entries(x.predictions).every(([key,value]) => x.draftPlan.some((step:any) => step.id === key) && sets.port.has(value as string)) || !idArray(x.completedStepIds) || !x.completedStepIds.every((id:string) => x.draftPlan.some((step:any) => step.id === id)) || !Array.isArray(x.recoveryClaims) || !x.recoveryClaims.every((claim:any) => exactKeys(claim,['materialId','streamId']) && sets.material.has(claim.materialId) && typeof claim.streamId === 'string') || !(x.currentRun === null || validRun(x.currentRun,x.missionId || undefined)) || typeof x.revisionReason !== 'string' || typeof x.sustainabilityReflection !== 'string') return false; return true; }
